# -*- coding: utf-8 -*-
"""recommendor_system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19PRvvbrGYitbgnrcExZuAFMSUeb3Sgnq
"""

# Necessary import statements:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import pairwise_distances

# Download dataset:
df = pd.read_csv("http://files.grouplens.org/datasets/movielens/ml-100k/u1.base",sep='\t',header=None, names=["userId", "movieId", "rating", "timestamp"])

# printdf.head()
print("shape", df.shape)

"""# Build a user to user similarity model"""

# find how many unique users and movies there are:
n_users = df.userId.unique().shape[0]
n_items = df.movieId.unique().shape[0]

print("unique users:", n_users)
print("unique movies:", n_items)

# train-test split the data:
train, test = train_test_split(df, test_size=0.20)

# calculate similarity between users and items:
train_matrix = np.zeros((n_users, n_items))
for line in train.itertuples():
  if line[2] > 1650:
    continue
  train_data_matrix[line[1]-1, line[2]-1] = line[3]

user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

def predict(ratings, similarity, type):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

# make predictions:
user_prediction = predict(train_matrix, user_similarity, type='user')
item_prediction = predict(train_matrix, item_similarity, type='item')

# Test the accuracy using an RMSE since the project will be assesed the same way:
# Not required for this hw