# -*- coding: utf-8 -*-
"""Iris_Random_Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZVbZvSN-plGD3UK9HITeifAqJm7mp6e
"""

# Necessary import statements:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# load the iris dataset: 
iris_data = load_iris() 

# Set x as flower characteristics and y as target values:
x = iris_data.data[:,[2,3] ]
y = iris_data.target.reshape(-1, 1)

# Split the data for training and testing:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

# Create a random forest classifier per Geron page 197.
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
rnd_clf.fit(train_x, train_y)
y_pred_rf = rnd_clf.predict(test_x)

# Find out how accurate the random forest generator is:
correct = 0
for i in range(len(y_pred_rf) ):
  if y_pred_rf[i] == test_y[i]:
    correct += 1
per_correct = correct/len(y_pred_rf)
print(per_correct)

