# -*- coding: utf-8 -*-
"""Iris_Decision_Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HrYZc13BxtxqlauM985EoMvJBKNbLWAr
"""

# Necessary import statements:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from google.colab import files

# Get key iris dataset data using only 2 characteristics:
iris = load_iris()
X = iris.data[:, 2:] # only using 2 features: petal lenth and petal width
y = iris.target

# Key tree code:
tree_clf = DecisionTreeClassifier(max_depth=5) # Textbook uses 2 as a max depth.
tree_clf.fit(X,y) # Fit data to tree

# Visualize the trained decision tree:
export_graphviz(
    tree_clf,
    out_file = "iris_tree.dot",
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    rounded=True,
    filled=True
)

# Download the out_file onto my desktop to see result:
files.download("iris_tree.dot")
# Use the following command to export the .dot file to .png: dot -Tpng iris_tree.dot -o iris_tree.png
# Comments on the png file:
# If one observes the the png they will see that setosas perfectly classify in the second level which makes sense since setosas are most distinguishable.
# Due to similarities between versicolors and vriginicas it took an additional 3 tree levels to perfectly classify the versicolors and virgincas.